name: Deploy Bicep file
on: 
  push:
    branches:
      - main
    paths:
      - main.bicep
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy RG
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./rg.bicep
        deploymentMode: Complete
        region: germanywestcentral

    - name: Deploy VM
      uses: azure/arm-deploy@v2
      with:
        resourceGroupName: rg-spuce-bites-website
        template: ./vm.bicep
        deploymentMode: Complete
        parameters: adminUsername=${{ secrets.ADMIN_USERNAME }} adminPasswordOrKey=${{ secrets.ADMIN_PASSWORD_OR_KEY }}